# This is a basic workflow to help you get started with Actions

name: first

# Controls when the workflow will run
on: push
  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step One
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Step Two
        run: env | sort
  job2:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step One
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Step Two
        run: "Get-ChildItem Env: | Sort-Object Name"
